language: node_js
services:
- rabbitmq
node_js:
- '4.2'
before_install:
- sudo apt-get update -qq
- sudo apt-get install pkg-config cmake openssl libc-ares-dev
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
install:
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd ..
- npm install
before_script:
- mosquitto -d
- npm install -g grunt-cli
script:
- npm test
deploy:
  provider: npm
  email: jononor@gmail.com
  skip_cleanup: true
  api_key:
    secure: lovNd++XUGKSGeO0ze6rI87Y/RCdEvOlD1Z4FzVaCbjD6meNiOygf4SrHdVMUa8Xe0kCBUc9MRVqKZEvvgJ/yLgv+LwwU6+jhecGMWmovVh0b7q3il7ixzdvR4Lyyl4YxNu2AJMFn6G/YzniNm5EwaIss5vkoUAijmfys5FQFMsj/IQp08u2PRusfSua0Nnx5FtMDS17k2bqheCE7rTMlHswHuHCrE0gabBZoMgLK1K3DGvROvvQzbMlMYrLLbT8Xdm08opqzIUYTHqo7fIZOFqPieuw9gPb6T/M3QY9k0UIflF/rh9hoCAdJRa/BT8pxwXmE2V0PxKGMCTzphfKQ1mfpqQCTM4jNPDSRhadkAe1JTas9PeP91IPSECcamN9soBW/3fUe4ji3UGpaJHmU97Owd3BBzNQl2PMoHUBmyI4C0QkwukjgyStky/oEFaL6uh/scA2Hrin1jsOv2sXEltjkogbRWspGv9q+1DfJkHeiYqpp44nU4Kb2dXVNFqYSVxNUNewRrY3hsH8K1cBK4x61jBOY5ItUNQ2a64GhZ7WyHr2gIPxwT33HD+4ksRnEknl6KU9qc+6kwdi7fERQ8nEyDUOv4ZWtvvoHXiwZzu7m7Xwhtj4RdJ2IEUniJlmHq7M/yr8FPGCP+AXQzBQq2BUPt3OUEWAYrlk0vfjFA4=
  on:
    tags: true
    repo: msgflo/msgflo-nodejs
