language: node_js
services:
- rabbitmq
node_js:
- '4.2'
before_install:
- sudo apt-get update -qq
- sudo apt-get install pkg-config cmake openssl libc-ares-dev
- wget http://mosquitto.org/files/source/mosquitto-1.3.1.tar.gz
install:
- tar xzf mosquitto-1.3.1.tar.gz
- cd mosquitto-1.3.1
- cmake .
- sudo make install
- cd ..
- npm install
before_script:
- mosquitto -d
- npm install -g grunt-cli
script:
- npm test
deploy:
  provider: npm
  email: jononor@gmail.com
  skip_cleanup: true
  api_key:
    secure: K+uFHsh/EgT6zKDdXJV+770WdXzuBaiLQkN1EI/JU5AfjOqw8cWI2ycbH9LWlOCcE29l/cVFL+ycx/1x69IwmAWk61TlwPXqT1KiDBn8lxEN2dPub/0Cr7iHP/XV60daao2TJS+KS44wS6MIMcwBNkbeCZXsOKQZjFR/qjlAM5kCCQO+cZBWC+m2k3w0KHRO+6AdAOke205iGrI0/ZHLNU96f0jhMtwy3oM2DQEwY6aerAVx6cBes9Cdqzn86qgOohP5XXVpllTzeBTt6WjIQsQB1PXFReYfN0Tfcsvg2bcOUMhc5Exj1p40/Q9gSNKZon/4kRQFKvut1+189qMga6JKA6wdYO8xltVgRgwGc6pyeXMrJHZ/vzxyOLCYTE/W15Kg61dXrzBi4Ke+1Bm7DGuYFvAanSgEboseNFCkKSNirDO2a2Xv2ldRlWQpgEOADhAczGSlmUTz2/UqMEwrvc1M+DyRnGD2zyDV4My23jGAKnI/vqFke3PvLjGa+GpzcvEYntEq2iCIDSaoaJH47d1T9Rj2/g5Vl9hw6bfkLZIFk46fUfU4KzZJHmxs3x7s0vijNY2DAT3TrLhIw20gMbQJBiAW1BCojgZ2B+OB/ChYQcxYJ2IQEJxsLBXFrlSC3tfXCzWgf7yjrwYsP3Hbj+AbP+74E7uwLh/eSDfrpCY=
  on:
    tags: true
    repo: msgflo/msgflo-nodejs
